name: Test build

on:
  push:
    branches: [ main, dev ]

  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: BlurFileEditor build
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      
      - name: Build BlurFileEditor
        run: |
           msbuild BlurFileEditor.sln
